services:
  - type: web
    name: salary-predictor
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.headless true
